apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: bookstore-testbed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: paritosh4495/csc8499-load-generator:latest
        imagePullPolicy: Always
        env:
        - name: INVENTORY_URL
          value: "http://inventory-service:8081/api/products"
        - name: ORDER_URL
          value: "http://order-service:8082/api/orders"
        - name: BROWSE_INTERVAL
          value: "0.2"
        - name: ORDER_INTERVAL
          value: "2.0"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
