apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "condition-a"
    target:
      kind: Deployment
      name: inventory-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "condition-a"
    target:
      kind: Deployment
      name: order-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "condition-a"
    target:
      kind: Deployment
      name: payment-service